ログイン者名表示のため、AdministratorControllerを変更
NobutakaYoshida/ex-emp-management-bugfix pull request #3
Opened 2021-11-16 08:58 UTC by NobutakaYoshida

ログイン者名表示のため、AdministratorControllerを変更しました

2021-11-16 23:47 UTC, NobutakaYoshida reviewed
ログイン者名表示のため、AdministratorControllerを変更しました。

2021-11-17 00:15 UTC, NobutakaYoshida reviewed
従業員一覧の並び替え。入社日順に変更。

2021-11-17 00:17 UTC, NobutakaYoshida reviewed
従業員一覧の入社日標記を「yyyy月MM月dd日」に変更。

2021-11-17 00:20 UTC, NobutakaYoshida reviewed
従業員情報詳細の年収標記に３ケタずつコンマを追加

2021-11-17 00:22 UTC, NobutakaYoshida reviewed
従業員詳細画面、パンくずリストのリンク切れ対応

2021-11-17 00:28 UTC, NobutakaYoshida reviewed
SQLインジェクション対策

2021-11-17 00:29 UTC, NobutakaYoshida reviewed
XSS対策

2021-11-17 00:32 UTC, NobutakaYoshida reviewed
Whitelabel Error Page対策

2021-11-17 01:10 UTC, hiroyukikanomata requested changes
コメントを書いたので、一部修正お願いします。

2021-11-17 01:10 UTC, hiroyukikanomata commented on src/main/resources/templates/employee/list.html
> +								<span th:text="${#dates.format(employee.hireDate, 'yyyy年MM月dd日')}">2016/12/1</span>
ok

2021-11-17 01:10 UTC, hiroyukikanomata commented on src/main/resources/templates/employee/detail.html
> +							      <span th:text="${#numbers.formatInteger(employee.salary, 2, 'COMMA') + '円'}">400000円</span>
(employee.salary, 2, 'COMMA')
の2つ目の引数は、給料が2桁未満の場合に0埋めが発生してしまいます。

（ありえないが、給料が9円とかなら、画面には「09」円と表示される）

なので、2ではなく、1に修正すると、ゼロ埋めが発生せず安心です。

2021-11-17 01:10 UTC, hiroyukikanomata commented on src/main/resources/templates/employee/detail.html
> +							      <span th:text="${employee.hireDate}">2012/11/29</span>
こちらも、「〜年〜月〜日」のように表示してあげると良いです。

2021-11-17 01:10 UTC, hiroyukikanomata commented on src/main/java/jp/co/sample/emp_management/repository/EmployeeRepository.java
> +		String sql = "SELECT id,name,image,gender,hire_date,mail_address,zip_code,address,telephone,salary,characteristics,dependents_count FROM employees ORDER BY hire_date DESC";
good

2021-11-17 01:10 UTC, hiroyukikanomata commented on src/main/java/jp/co/sample/emp_management/repository/AdministratorRepository.java
> +		SqlParameterSource param = new MapSqlParameterSource().addValue("mailAddress", mailAddress).addValue("password", password);
SQLインジェクション対策Good

2021-11-17 01:15 UTC, NobutakaYoshida reviewed
入社日と数値の表記を修正しました

2021-11-17 02:18 UTC, merged